# Generated by Django 4.2.7 on 2024-01-10 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_comment_active_alter_comment_datetime_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('address', models.CharField(max_length=700, verbose_name='address')),
                ('order_notes', models.CharField(blank=True, max_length=500, verbose_name='order_notes')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='تومان')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='product')),
            ],
        ),
    ]
